#!/bin/sh

# Read statements stop the upload from happening until I can approve that the video has done encoding itself
read -p "Press enter to run recordmydesktop." i
mate-terminal -e ~/auto/scripts/rcd
read -p "Press enter when it's done." j
